[package]
name = "core"
edition.workspace = true
repository.workspace = true
version.workspace = true
readme.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
core_assets = { path = "../core_assets", default-features = false, features = [] }
crossbeam-channel = "*"
image = { version = "*", default-features = false }
serde = { version = "*", default-features = false }
rmp-serde = { version = "1.3.0", optional = true }
serde_json = { version = "1.0.140", optional = true }
bevy = { workspace = true, features = [
  "bevy_state",
  "bevy_log",
  "bevy_render",
  "bevy_core_pipeline",
  "bevy_sprite",
  "bevy_asset",
  "bevy_window",
  "serialize"
] }
semver = { version = "1.0.26", features = ["serde"] }
tracing-appender = "0.2.3"
tracing-subscriber = { version = "0.3.19", features = ["json"] }

[features]
default = ["msgpack"]

dev = [
  "bevy/trace",
  "bevy/track_location",
  "bevy/bevy_dev_tools",
]

msgpack = ["dep:rmp-serde"]
json = ["dep:serde_json"]

windows = []
linux = []
macos = []
